### PR TITLE
Add Types

### LINKED ISSUE #51: no types for typescript
is there any packages that help to generate types for this package

### PR DESCRIPTION
**Pull request by Phillip9587**
closes #51 #56

### CODE REVIEW

**Comment by Phillip9587** [comment]
@stepankuzmin Sorry for pinging you directly but can we maybe get this merged and released? Would help a lot

**Review by stepankuzmin — APPROVED** [review]
Looks good to me. Thanks for the contribution, @Phillip9587!

**Comment by Phillip9587** [comment]
@stepankuzmin Can you release a version with the types included?

**Comment by stepankuzmin** [comment]
Hey @Phillip9587,
Thanks for your patience! We've published `@mapbox/mapbox-gl-language` [v1.0.1](https://www.npmjs.com/package/@mapbox/mapbox-gl-language)

**Pull request merged**
