### PR TITLE
Update language when changing style

### PR DESCRIPTION
**Pull request by ryanhamley**
Closes https://github.com/mapbox/mapbox-gl-language/issues/26

### CODE REVIEW

**Comment by WilliamPriorielloGarda** [comment]
If this solution is correct, we are also waiting on it in a new npm version.
Thanks

**Comment by nasreddineskandrani** [comment]
Hi @ryanhamley,
Can you please proceed with this merge?

Thank you in advance

**Review by SnailBones — APPROVED** [review]
LGTM 👍

**Comment by nasreddineskandrani** [comment]
thanks

**Comment by ryanhamley** [comment]
Thanks for the patience everyone. I'm working on getting a new release out asap.

**Pull request merged**
